theme: jekyll-theme-cayman
title: Здорово! Вы находитесь на сайте проекта ModelAuthApp
description: Это учебный проект, моделирующий процесс Аутентификации, Авторизации и Аккаунтинга пользователя. Приложение представляет собой консольную утилиту, принимающую на вход аргументы.
